site_name: PyConZA Documentation
nav:
  - Home: index.md
  - Communication:
      - Overview: communication.md
      - Plugging into Communities: communication/plugging-into-communities.md
  - Onboarding New Organisers: onboarding-organisers.md
